PowerNMS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

app_name = 'PowerNMS'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('Powerapp.urls')),
]

Powerapp/urls.py
from django.conf.urls import include, url
from django.urls import path

from . import views
from Powerapp.views import *


app_name = "Powerapp"

urlpatterns=[
    path('', ListModules.as_view(),name='default' ),
    path('addmodule/', CreateModule.as_view(),name='addmodule' ),
    path('deletemodule/<str:pk>/', DeleteModule.as_view(), name='deletemodule'),
    path('updatemodule/<str:pk>', UpdateModule.as_view(), name='updatemodule' ),
    path('detailmodule/<str:pk>', DetailModule.as_view(), name='detailmodule' ),
    path('listmodule', ListModules.as_view(), name = 'listmodules'),
    path('listmodule', ListModules.as_view(), name = 'home'),
    path('btsoff/<str:ip>', BTSOFF.as_view(), name = 'btsoff'),
    path('btson/<str:ip>', BTSON.as_view(), name = 'btson'),
    path('hvacon/<str:ip>', HVACON.as_view(), name = 'hvacon'),
    path('hvacoff/<str:ip>', HVACOFF.as_view(), name = 'hvacoff'),
    path('genon/<str:ip>', GENON.as_view(), name = 'genon'),
    path('genoff/<str:ip>', GENOFF.as_view(), name = 'genoff'),
    path('update/', ModuleUpdateView.as_view(), name = 'moduleview'),
    path('hello/', ModuleHelloView.as_view(), name = 'helloview'),
    path('history/<str:pk>', HistoryView.as_view(), name = 'history'),

]

Powerapp/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
# Create your models here.
class Module(models.Model):
    """
    Powermodule model for the raspberry pi device onsite
    """

    ipaddress = models.CharField(max_length=200,null=False,primary_key=True) # ip addresss for the power module onsite
    port = models.CharField(max_length=4,null=True) # the power module port
    online = models.BooleanField(default=False) # onine status of the module
    name = models.CharField(max_length=200,null=True) # the site name of the device module
    btsstatus = models.BooleanField(default=False) # the BTS status of the site on or off
    hvacstatus = models.BooleanField(default=False) # the HVAC status of the site on or off
    genstatus = models.BooleanField(default=False) # the GEN status of the site on or off



    def __str__(self):
        return self.ipaddress

    def get_absolute_url(self):

        return reverse('Powerapp:detailmodule', kwargs={'pk':self.pk})

    @property
    def online_status(self):
        lastupdate = UpdateTracker.objects.filter(module=self).latest('time')
        last_update_time = lastupdate.time.replace(tzinfo=None)
        current_time = datetime.now().replace(tzinfo=None)
        print(current_time)
        print(last_update_time)


        difference = current_time - last_update_time
        difference_in_minutes = difference.seconds/60 - 120
        print(difference_in_minutes)

        if difference_in_minutes > 3 :
            return False
        else:
            return True



class UpdateTracker(models.Model):
    """
    A model to track all updates from models
    """
    module = models.ForeignKey(Module,on_delete=models.CASCADE)
    btsstatus = models.BooleanField(default=False) # the BTS status of the site on or off
    hvacstatus = models.BooleanField(default=False) # the HVAC status of the site on or off
    genstatus = models.BooleanField(default=False,null=True) # the GEN status of the site on or off
    mainsstatus = models.BooleanField(default=False, null=True) # the MAINS status of the site on or off
    time = models.DateTimeField(auto_now_add=True) # update time update was received
    delta = models.BooleanField(default=False) # indicate if changed or not

    def serialize(self):
        ans = {'BTS':self.btsstatus,'HVAC':self.hvacstatus,'GEN':self.genstatus}
        return ans

Powerapp/forms.py
from django import forms
from .models import Module
class ModuleCreateForm(forms.ModelForm):

    class Meta:
        model = Module
        fields = ('ipaddress','port','name')

Powerapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from .forms import ModuleCreateForm
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .powermodule import Powermodule, get_module_instance, UpdateRecorder
from .models import Module, UpdateTracker
import json


class CreateModule(CreateView):
    """
    View to create a module model
    """
    form_class = ModuleCreateForm
    template_name = 'Powerapp/createmodule.html'
    success_url = reverse_lazy('Powerapp:home')


class ListModules(ListView):
    """
    View to list all modules on the NMS
    """
    model = Module
    template_name = 'Powerapp/listmodules.html'
    context_object_name = 'modules'


class UpdateModule(UpdateView):
    """
    View to update module properties
    """
    model = Module
    form_class = ModuleCreateForm
    template_name = 'Powerapp/createmodule.html'


class DetailModule(DetailView):
    """
    View to show details of a module
    """
    model = Module
    template_name = 'Powerapp/detailmodule.html'


class DeleteModule(DeleteView):
    """
    View to delete a module
    """
    model = Module
    success_url = reverse_lazy('Powerapp:home')


class BTSOFF(View):
    """
    Class to handle BTS OFF controll
    """

    def get(self,request,*args,**kwargs):

        module_ip = kwargs['ip'] # get ip address of module
        module = Powermodule(module_ip) # create a powermodule instance
        response = module.setBTSoff()
        # check if response is OK
        if response.status_code == 200:
                module.update_db_bts(False)

        # return the detail view for the module
        return HttpResponseRedirect(reverse_lazy('Powerapp:detailmodule',kwargs={'pk':module.id}))


class BTSON(View):
    """
    Class to handle BTS ON control
    """

    def get(self,request,*args,**kwargs):

        module_ip = kwargs['ip'] # get ip address of module
        module = Powermodule(module_ip) # create a powermodule instance
        response = module.setBTSon()
        # check if response is OK
        if response.status_code == 200:
                module.update_db_bts(True)

        # return the detail view for the module
        return HttpResponseRedirect(reverse_lazy('Powerapp:detailmodule',kwargs={'pk':module.id}))


class HVACOFF(View):
    """
    Class to handle HVAC OFF control
    """

    def get(self,request,*args,**kwargs):

        module_ip = kwargs['ip'] # get ip address of module
        module = Powermodule(module_ip) # create a powermodule instance
        response = module.setHVACoff()
        # check if response is OK
        if response.status_code == 200:
                module.update_db_hvac(False)
        # return the detail view for the module
        return HttpResponseRedirect(reverse_lazy('Powerapp:detailmodule',kwargs={'pk':module.id}))


class  HVACON(View):
    """
    Class to handle HVAC ON control
    """

    def get(self,request,*args,**kwargs):

        module_ip = kwargs['ip'] # get ip address of module
        module = Powermodule(module_ip) # create a powermodule instance
        response = module.setHVACon()
        # check if response is OK
        if response.status_code == 200:
                module.update_db_hvac(True)
        # return the detail view for the module
        return HttpResponseRedirect(reverse_lazy('Powerapp:detailmodule',kwargs={'pk':module.id}))

class GENOFF(View):
    """
    Class to handle GEN OFF control
    """

    def get(self,request,*args,**kwargs):

        module_ip = kwargs['ip'] # get ip address of module
        module = Powermodule(module_ip) # create a powermodule instance
        response = module.setGENoff()
        # check if response is OK
        if response.status_code == 200:
                module.update_db_gen(False)
        # return the detail view for the module
        return HttpResponseRedirect(reverse_lazy('Powerapp:detailmodule',kwargs={'pk':module.id}))


class GENON(View):
    """
    Class to handle GEN ON control
    """

    def get(self,request,*args,**kwargs):

        module_ip = kwargs['ip'] # get ip address of module
        module = Powermodule(module_ip) # create a powermodule instance
        response = module.setGENon()
        # check if response is OK
        if response.status_code == 200:
                module.update_db_gen(True)
        # return the detail view for the module
        return HttpResponseRedirect(reverse_lazy('Powerapp:detailmodule',kwargs={'pk':module.id}))

class ModuleUpdateView(View):
    """
    The view for receiving update requests from modules
    """

    def post(self,request,*args,**kwargs):
        """
        Method to process posts from the power module

        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        json_string = request.body.decode('utf-8') # extract the json data
        data = json.loads(json_string) # load json string to a dict
        module_ip = data['module'] # module ip address

        pm = get_module_instance(module_ip) # create a powermodule instance

        if pm.ipaddress is not None:
            try:
                pm.update_rcvd(data) # pass the received dict to the module and update db
                data = {'ACK':'OK'}
            except:
                data = {'ACK':'NOK'}
        else :
            # do not process unkown module requests, log the miscellaneous event
            pass
        return JsonResponse(data)


class HistoryView(ListView):
    """
    View to list all modules on the NMS
    """
    model = UpdateTracker
    template_name = 'Powerapp/listmodule_records.html'
    context_object_name = 'updates'

    def get_queryset(self):
        return UpdateTracker.objects.filter(module__ipaddress=self.kwargs['pk']).order_by('-time')[:20]

class ModuleHelloView(View):
    """
    Class to handle hello packets from the module
    """

    @method_decorator(csrf_exempt)  # required
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def post(self,request,*args,**kwargs):
        """
        Handle POST data from the module

        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        json_string = request.body.decode('utf-8') # extract the json data
        data = json.loads(json_string) # load json string to a dict
        updaterecorder = UpdateRecorder(data) # create update recorder instance
        new_record = updaterecorder.save() # save the record

        if new_record.module is not None:
            ack = {'ACK':'OK'} # no error occured
        else :
            ack = {'ACK':'ER'}  # an error occured

        try:
            reply = new_record.serialize() # convert to JSON
            reply = {**ack,**reply} # merge dictionaries
        except Exception as e:
            print(e)
            reply=ack



        return JsonResponse(reply)

Powerapp/templates/Powerapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Network Power Monitor</title>

  <!-- Custom fonts for this template -->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">


  <!-- Custom styles for this template -->
  <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">

  <!-- Custom styles for this page -->
  <link href="/static/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>





<body id="page-top">
  <!-- Page Wrapper -->
  <div id="wrapper">

          <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
<div id="content">
{% include "Powerapp/topbar.html" %}
            <!-- Begin Page Content -->
        <div class="container-fluid">
{% block content %}
{% endblock %}
        </div>
    <!-- End page content -->
</div>
  </div>
  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/js/sb-admin-2.min.js"></script>

  <!-- Page level plugins -->
  <script src="/static/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/vendor/datatables/dataTables.bootstrap4.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="/static/js/demo/datatables-demo.js"></script>

</body>
</html>

Powerapp/templates/Powerapp/createmodule.html
{% extends 'Powerapp/base.html' %}
{% block content %}
<div class="card-body">
<h3>Create a Power module</h3>
<div class ="row">
<div class="col-lg-8">
<form role="form" method="POST" class="post-form">{% csrf_token %}
                   {% for field in form.visible_fields %}
      <div class="form-group">
        <label  for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

</div>
</div>
</div>

{% endblock %}

Powerapp/templates/Powerapp/detailmodule.html
{% extends 'Powerapp/base.html' %}

{% block content %}
<div class="container-fluid" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<h2>Details for {{ module.name }}</h2>
    <div class="row">

        <div class="card border-secondary mb-3" id="module_properties">
            <div class="card-body">
                <div class="card-title">
                    <h3>Properties</h3>
                 </div>
                <div class="row">
                    <div class="col-md-3">
                        <strong>Name:</strong>
                        <span>{{ module.name}}</span>
                    </div>
                    <div class="col-md-3">
                        <strong>Communication Address:</strong>
                        <span>{{ module.ipaddress}}</span>
                    </div>
                    <div class="col-md-3">
                        <label><strong>Communication Status:</strong></label>
                                  <span> {% if  module.online_status %}
                                        Online
                                    {% else %}
                                        Offline
                                    {%endif %}
                                  </span>
                    </div>
                    <div class="col-md-3">
                        <label><strong>Battery Threshold:</strong></label>
                        <span>
                            {% if module.battery_threshold %}
                                {{ module.battery_threshold}}
                            {% else %}
                                NA
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card border-secondary mb-3" id="module_status">
            <div class="card-body">
                <div class="card-title">
                    <h3>Status</h3>
                </div>
            <div class="row">
                <div class="col-md-3">
                    <strong>BTS:</strong>
                    <span>
                                   {% if  module.btsstatus %}
                ON
                {% else %}
                OFF
                {%endif %}
                    </span>
                </div>
                <div class="col-md-3">
                    <strong>HVAC:</strong>
                    <span>
                                   {% if  module.hvacstatus %}
                ON
                {% else %}
                OFF
                {%endif %}
                    </span>
                </div>
                <div class="col-md-3">
                    <strong>GEN:</strong>
                    <span>
                                   {% if  module.genstatus %}
                ON
                {% else %}
                OFF
                {%endif %}
                    </span>
                </div>
                <div class="col-md-3">
                    <strong>Mains:</strong>
                    <span>
                        {% if module.mainsstatus %}
                            ON
                        {% else %}
                            OFF
                        {% endif %}
                    </span>
                </div>
        </div>
        </div>
        </div>
    </div>
    {% if module.online_status %}
<div>
    {% if module.btsstatus %}
    <a class = "btn btn-warning" href="{% url 'Powerapp:btsoff' ip=module.ipaddress %}"> BTSoff</a>
    {% else %}
    <a class = "btn btn-primary" href="{% url 'Powerapp:btson' ip=module.ipaddress %}"> BTSon</a>
    {% endif %}
    {% if module.hvacstatus %}
    <a class = "btn btn-warning" href="{% url 'Powerapp:hvacoff' ip=module.ipaddress %}">  HVACoff</a>

    {% else %}
    <a class = "btn btn-primary" href="{% url 'Powerapp:hvacon' ip=module.ipaddress %}">  HVACon</a>
    {% endif %}
    {% if module.genstatus %}
    <a class = "btn btn-warning" href="{% url 'Powerapp:genoff' ip=module.ipaddress %}">  GENoff</a>

    {% else %}
    <a class = "btn btn-primary " href="{% url 'Powerapp:genon' ip=module.ipaddress %}">  GENon</a>
    {% endif %}

</div>
    {% else %}
<div>
    {% if module.btsstatus %}
    <a class = "btn btn-warning disabled" href="{% url 'Powerapp:btsoff' ip=module.ipaddress %}"> BTSoff</a>
    {% else %}
    <a class = "btn btn-primary disabled" href="{% url 'Powerapp:btson' ip=module.ipaddress %}"> BTSon</a>
    {% endif %}
    {% if module.hvacstatus %}
    <a class = "btn btn-warning disabled" href="{% url 'Powerapp:hvacoff' ip=module.ipaddress %}">  HVACoff</a>

    {% else %}
    <a class = "btn btn-primary disabled" href="{% url 'Powerapp:hvacon' ip=module.ipaddress %}">  HVACon</a>
    {% endif %}
    {% if module.genstatus %}
    <a class = "btn btn-warning disabled" href="{% url 'Powerapp:genoff' ip=module.ipaddress %}">  GENoff</a>

    {% else %}
    <a class = "btn btn-primary disabled" href="{% url 'Powerapp:genon' ip=module.ipaddress %}">  GENon</a>
    {% endif %}

</div>
    {% endif %}
</div>
{% endblock %}

Powerapp/templates/Powerapp/listmodule_records.html
{% extends 'Powerapp/base.html' %}

{% block content %}

<div class="card-body">
    <h2> {{ record.module }}Updates History</h2>
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
    <th>Name</th>
    <th>BTS</th>
    <th>HVAC</th>
    <th>Time</th>
    <th></th>
    </thead>
    <tbody>
        {% for record in updates %}
    <tr>
        <td><a href="{% url 'Powerapp:detailmodule' pk=record.module.pk%}">{{ record.module.name}}</a></td>
        <td>
                     {% if record.btsstatus %}
            <p class="btn btn-primary">Switched ON</p>
            {% else %}
             <p class = "btn btn-warning">Switched OFF</p>
            {% endif %}
        </td>

        </td>
        <td>
            {% if record.hvacstatus %}
            <p class="btn btn-primary">Switched ON</p>
            {% else %}
            <p class = "btn btn-warning">Switched OFF</p>
            {% endif %}
        </td>

        </td>
        <td>{{ record.time}}</td>
    </tr>
        {% endfor %}

    </tbody>
</table>
    </div>
</div>
{% endblock %}

Powerapp/templates/Powerapp/listmodules.html
{% extends 'Powerapp/base.html' %}

{% block content %}

<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
    <th>Name</th>
    <th>IP address</th>
    <th>Port</th>
    <th>Communication Status</th>
    <th>BTS</th>
    <th>HVAC</th>
    <th>GEN</th>
    <th></th>
    <th></th>
    <th></th>
    </thead>
    <tbody>
        {% for module in modules %}
    <tr>
        <td><a href="{% url 'Powerapp:detailmodule' pk=module.pk%}">{{ module.name}}</a></td>
        <td>{{ module.ipaddress}}</td>
        <td>{{ module.port}}</td>
        <td>           {% if module.online_status %}
            Online
            {% else %}
            Offline
            {%endif %}</td>
        <td>
            {% if module.btsstatus %}
            ON
            {% else %}
            OFF
            {% endif %}
        </td>
        <td>            {% if module.hvacstatus %}
            ON
            {% else %}
            OFF
            {% endif %}</td>
        <td>            {% if module.genstatus %}
            ON
            {% else %}
            OFF
            {% endif %}</td>
        <td> <a href="{% url 'Powerapp:deletemodule' pk=module.pk %}">Delete</a></td>
        <td> <a href="{% url 'Powerapp:updatemodule' pk=module.pk %}">Edit</a></td>
        <td> <a href="{% url 'Powerapp:history' pk=module.ipaddress %}">Updates</a></td>
    </tr>
        {% endfor %}

    </tbody>
</table>
    </div>
</div>
{% endblock %}

Powerapp/templates/Powerapp/module_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

Powerapp/templates/Powerapp/topbar.html
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Links for other parts of the site -->
            <li class="nav-item"> <a class="nav-link btn" href ="{% url 'Powerapp:listmodules'%}"> Modules</a></li>
            <li class="nav-item"> <a class="nav-link btn" href ="{% url 'Powerapp:addmodule'%}"> Create</a></li>

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter"></span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>

                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter"></span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>

                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">user</span>
                <img class="img-profile rounded-circle" src="">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->